-- Gen8 Inventory initial schema
-- Compatible with the current application while keeping browser-facing database access closed.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'staff'
    check (role in ('admin', 'staff', 'viewer')),
  approved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index users_email_lower_uq
  on public.users (lower(email));

create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create table public.clients (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) > 0),
  logo_url text,
  barcode text,
  user_id uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index clients_barcode_uq
  on public.clients (barcode)
  where barcode is not null and length(trim(barcode)) > 0;

create index clients_user_id_idx on public.clients (user_id);
create index clients_name_idx on public.clients (name);

create trigger clients_set_updated_at
before update on public.clients
for each row execute function public.set_updated_at();

create table public.user_clients (
  user_id uuid not null references public.users(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, client_id)
);

create index user_clients_client_id_idx
  on public.user_clients (client_id);

create table public.locations (
  id bigint generated by default as identity primary key,
  code text not null check (length(trim(code)) > 0),
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index locations_code_lower_uq
  on public.locations (lower(code));

create trigger locations_set_updated_at
before update on public.locations
for each row execute function public.set_updated_at();

create table public.items (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  part_number text not null check (length(trim(part_number)) > 0),
  lot_number text,
  name text,
  description text,
  barcode text,
  reorder_level integer
    check (reorder_level is null or reorder_level >= 0),
  low_stock_threshold integer
    check (low_stock_threshold is null or low_stock_threshold >= 0),
  alert_enabled boolean not null default true,
  alert_acknowledged_at timestamptz,
  attributes jsonb not null default '{}'::jsonb
    check (jsonb_typeof(attributes) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  unique (client_id, id)
);

create unique index items_client_part_lot_uq
  on public.items (
    client_id,
    part_number,
    coalesce(nullif(trim(lot_number), ''), '')
  );

create unique index items_barcode_uq
  on public.items (barcode)
  where barcode is not null and length(trim(barcode)) > 0;

create index items_client_id_idx on public.items (client_id);
create index items_part_number_idx on public.items (part_number);
create index items_client_part_idx on public.items (client_id, part_number);
create index items_attributes_gin_idx on public.items using gin (attributes);

create trigger items_set_updated_at
before update on public.items
for each row execute function public.set_updated_at();

create table public.inventory (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(id) on delete cascade,
  location_id bigint not null references public.locations(id) on delete restrict,
  quantity integer not null default 0 check (quantity >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (item_id, location_id)
);

create index inventory_location_id_idx on public.inventory (location_id);
create index inventory_item_id_idx on public.inventory (item_id);

create trigger inventory_set_updated_at
before update on public.inventory
for each row execute function public.set_updated_at();

create table public.item_barcodes (
  id bigint generated by default as identity primary key,
  client_id bigint not null,
  item_id bigint not null,
  barcode text not null check (length(trim(barcode)) > 0),
  symbology text,
  created_at timestamptz not null default now(),
  constraint item_barcodes_item_client_fk
    foreign key (client_id, item_id)
    references public.items(client_id, id)
    on delete cascade,
  constraint item_barcodes_barcode_uq unique (barcode)
);

create index item_barcodes_item_id_idx on public.item_barcodes (item_id);
create index item_barcodes_client_id_idx on public.item_barcodes (client_id);

alter table public.users enable row level security;
alter table public.clients enable row level security;
alter table public.user_clients enable row level security;
alter table public.locations enable row level security;
alter table public.items enable row level security;
alter table public.inventory enable row level security;
alter table public.item_barcodes enable row level security;

revoke all on table public.users from anon, authenticated;
revoke all on table public.clients from anon, authenticated;
revoke all on table public.user_clients from anon, authenticated;
revoke all on table public.locations from anon, authenticated;
revoke all on table public.items from anon, authenticated;
revoke all on table public.inventory from anon, authenticated;
revoke all on table public.item_barcodes from anon, authenticated;

grant usage on schema public to service_role;
grant all privileges on table public.users to service_role;
grant all privileges on table public.clients to service_role;
grant all privileges on table public.user_clients to service_role;
grant all privileges on table public.locations to service_role;
grant all privileges on table public.items to service_role;
grant all privileges on table public.inventory to service_role;
grant all privileges on table public.item_barcodes to service_role;
grant usage, select on all sequences in schema public to service_role;

alter default privileges in schema public
  revoke all on tables from anon, authenticated;

alter default privileges in schema public
  grant all on tables to service_role;

alter default privileges in schema public
  grant usage, select on sequences to service_role;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'client-logos',
  'client-logos',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;
