-- Phase 2: database-backed inventory profiles, typed custom fields,
-- client display columns, default locations, and reusable import templates.

begin;

create table if not exists public.client_inventory_settings (
  client_id bigint primary key references public.clients(id) on delete cascade,
  profile_key text not null default 'general'
    check (profile_key in ('general', 'resin', 'molded_parts', 'genmark_components')),
  default_uom text,
  default_location_id bigint references public.locations(id) on delete set null,
  display_columns jsonb not null default '[]'::jsonb
    check (jsonb_typeof(display_columns) = 'array'),
  field_definitions jsonb not null default '[]'::jsonb
    check (jsonb_typeof(field_definitions) = 'array'),
  import_aliases jsonb not null default '{}'::jsonb
    check (jsonb_typeof(import_aliases) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists client_inventory_settings_profile_idx
  on public.client_inventory_settings (profile_key);

create index if not exists client_inventory_settings_default_location_idx
  on public.client_inventory_settings (default_location_id)
  where default_location_id is not null;

drop trigger if exists client_inventory_settings_set_updated_at
  on public.client_inventory_settings;
create trigger client_inventory_settings_set_updated_at
before update on public.client_inventory_settings
for each row execute function public.set_updated_at();

create table if not exists public.client_import_templates (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  sheet_name text,
  header_row integer check (header_row is null or header_row >= 1),
  column_mapping jsonb not null default '{}'::jsonb
    check (jsonb_typeof(column_mapping) = 'object'),
  default_location_id bigint references public.locations(id) on delete set null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, name)
);

create unique index if not exists client_import_templates_one_default_uq
  on public.client_import_templates (client_id)
  where is_default;

create index if not exists client_import_templates_client_idx
  on public.client_import_templates (client_id, name);

drop trigger if exists client_import_templates_set_updated_at
  on public.client_import_templates;
create trigger client_import_templates_set_updated_at
before update on public.client_import_templates
for each row execute function public.set_updated_at();

-- Seed settings for existing clients. Names are used only for a conservative
-- initial preset; administrators can change the profile from the app.
insert into public.client_inventory_settings (
  client_id,
  profile_key,
  default_uom,
  display_columns,
  field_definitions,
  import_aliases
)
select
  client.id,
  case
    when client.name ilike '%genmark%' or client.name ilike '%gen mark%'
      then 'genmark_components'
    when client.name ilike '%resin%'
      then 'resin'
    when client.name ilike '%vizgen%' or client.name ilike '%vgn%'
      then 'molded_parts'
    else 'general'
  end,
  case
    when client.name ilike '%genmark%' or client.name ilike '%gen mark%'
      then 'ea'
    when client.name ilike '%resin%'
      then 'lb'
    when client.name ilike '%vizgen%' or client.name ilike '%vgn%'
      then 'pieces'
    else null
  end,
  case
    when client.name ilike '%genmark%' or client.name ilike '%gen mark%' then
      '["part_number","description","manufacturer_part_number","vendor_item_number","category","lot_number","batch_number","inventory_location","total_quantity","uom","minimum_quantity","reorder_level","weekly_demand","weeks_on_hand","suggested_reorder","status","priority"]'::jsonb
    when client.name ilike '%resin%' then
      '["part_number","name","manufacturer","lot_number","material_type","color","additive","inventory_location","total_quantity","uom","status"]'::jsonb
    when client.name ilike '%vizgen%' or client.name ilike '%vgn%' then
      '["part_number","description","revision","lot_number","mold_number","cavity","condition","inventory_location","total_quantity","uom","status"]'::jsonb
    else
      '["part_number","name","description","lot_number","inventory_location","total_quantity","uom","status"]'::jsonb
  end,
  case
    when client.name ilike '%genmark%' or client.name ilike '%gen mark%' then
      '[
        {"key":"manufacturer_part_number","label":"Manufacturer Part Number","type":"text","required":false},
        {"key":"vendor_item_number","label":"Vendor Item Number","type":"text","required":false},
        {"key":"category","label":"Category","type":"text","required":false},
        {"key":"usage_per_assembly","label":"Usage per Assembly","type":"decimal","required":false},
        {"key":"weekly_demand","label":"Weekly Demand","type":"decimal","required":false},
        {"key":"minimum_quantity","label":"Minimum Quantity","type":"decimal","required":false},
        {"key":"reorder_quantity","label":"Reorder Quantity","type":"decimal","required":false},
        {"key":"target_quantity","label":"Target Quantity","type":"decimal","required":false},
        {"key":"batch_number","label":"Batch Number","type":"text","required":false},
        {"key":"notes","label":"Notes","type":"long_text","required":false}
      ]'::jsonb
    when client.name ilike '%resin%' then
      '[
        {"key":"label_name","label":"Label Name","type":"text","required":false},
        {"key":"manufacturer","label":"Manufacturer","type":"text","required":false},
        {"key":"material_type","label":"Material Type","type":"text","required":false},
        {"key":"color","label":"Color","type":"text","required":false},
        {"key":"additive","label":"Additive","type":"text","required":false},
        {"key":"on_order","label":"On Order","type":"decimal","required":false}
      ]'::jsonb
    when client.name ilike '%vizgen%' or client.name ilike '%vgn%' then
      '[
        {"key":"drawing_number","label":"Drawing Number","type":"text","required":false},
        {"key":"revision","label":"Revision","type":"text","required":false},
        {"key":"mold_number","label":"Mold Number","type":"text","required":false},
        {"key":"cavity","label":"Cavity","type":"text","required":false},
        {"key":"condition","label":"Condition","type":"select","required":false,"options":["Accepted","Quarantine","Hold","Rejected"]},
        {"key":"inspection_status","label":"Inspection Status","type":"select","required":false,"options":["Not Inspected","Passed","Failed","Conditional"]},
        {"key":"received_date","label":"Received Date","type":"date","required":false}
      ]'::jsonb
    else '[]'::jsonb
  end,
  '{}'::jsonb
from public.clients as client
on conflict (client_id) do nothing;

alter table public.client_inventory_settings enable row level security;
alter table public.client_import_templates enable row level security;

revoke all on table public.client_inventory_settings from anon, authenticated;
revoke all on table public.client_import_templates from anon, authenticated;

grant all privileges on table public.client_inventory_settings to service_role;
grant all privileges on table public.client_import_templates to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.client_inventory_settings is
  'Shared client inventory profile, display columns, typed custom fields, and import defaults.';

comment on table public.client_import_templates is
  'Reusable workbook sheet/header/column mappings for a client.';

commit;
