-- Smart Receiving + universal physical-container model.
-- Adds product master data, receipts/documents, quality disposition, and
-- parent/child container traceability without replacing the existing items table.

begin;

-- ---------------------------------------------------------------------------
-- Product master
-- ---------------------------------------------------------------------------

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  part_number text not null check (length(trim(part_number)) > 0),
  name text,
  description text,
  manufacturer text,
  manufacturer_part_number text,
  vendor_item_number text,
  profile_key text not null default 'general',
  default_uom text,
  active boolean not null default true,
  attributes jsonb not null default '{}'::jsonb check (jsonb_typeof(attributes) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists products_client_part_lower_uq
  on public.products (client_id, lower(trim(part_number)));
create index if not exists products_client_active_idx
  on public.products (client_id, active, part_number);
create index if not exists products_manufacturer_part_idx
  on public.products (client_id, lower(trim(manufacturer_part_number)))
  where manufacturer_part_number is not null;
create index if not exists products_vendor_item_idx
  on public.products (client_id, lower(trim(vendor_item_number)))
  where vendor_item_number is not null;
create index if not exists products_attributes_gin_idx
  on public.products using gin (attributes);

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create table if not exists public.product_aliases (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  alias text not null check (length(trim(alias)) > 0),
  alias_type text not null default 'supplier_text',
  supplier_name text,
  created_at timestamptz not null default now()
);

create unique index if not exists product_aliases_client_alias_lower_uq
  on public.product_aliases (client_id, lower(trim(alias)));
create index if not exists product_aliases_product_idx
  on public.product_aliases (product_id);

-- ---------------------------------------------------------------------------
-- Receiving documents and receipt records
-- ---------------------------------------------------------------------------

create sequence if not exists public.g8_receipt_seq start with 1;

create table if not exists public.receipts (
  id bigint generated by default as identity primary key,
  receipt_number text not null,
  client_id bigint not null references public.clients(id) on delete cascade,
  supplier_name text,
  po_number text,
  packing_slip_number text,
  coc_number text,
  received_date date not null default current_date,
  received_by_user_id uuid references public.users(id) on delete set null,
  received_by_email text,
  status text not null default 'draft',
  notes text,
  extraction_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint receipts_status_ck check (status in ('draft', 'received', 'cancelled'))
);

create unique index if not exists receipts_number_uq on public.receipts (receipt_number);
create index if not exists receipts_client_created_idx on public.receipts (client_id, created_at desc);

drop trigger if exists receipts_set_updated_at on public.receipts;
create trigger receipts_set_updated_at
before update on public.receipts
for each row execute function public.set_updated_at();

create or replace function public.assign_g8_receipt_number()
returns trigger
language plpgsql
as $$
begin
  if new.receipt_number is null or length(trim(new.receipt_number)) = 0 then
    new.receipt_number := 'RCV-' || to_char(current_date, 'YYYY') || '-' ||
      lpad(nextval('public.g8_receipt_seq')::text, 6, '0');
  end if;
  return new;
end
$$;

drop trigger if exists receipts_assign_number on public.receipts;
create trigger receipts_assign_number
before insert on public.receipts
for each row execute function public.assign_g8_receipt_number();

create table if not exists public.receipt_lines (
  id bigint generated by default as identity primary key,
  receipt_id bigint not null references public.receipts(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  lot_number text,
  batch_number text,
  quantity numeric(14,3) not null check (quantity >= 0),
  uom text,
  container_count integer not null default 1 check (container_count > 0),
  package_type text,
  quality_status text not null default 'pending_inspection',
  line_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint receipt_lines_quality_ck check (
    quality_status in ('pending_inspection', 'released', 'hold', 'quarantine', 'rejected')
  )
);

create index if not exists receipt_lines_receipt_idx on public.receipt_lines (receipt_id);
create index if not exists receipt_lines_product_lot_idx on public.receipt_lines (product_id, lot_number);

create table if not exists public.receipt_documents (
  id bigint generated by default as identity primary key,
  receipt_id bigint references public.receipts(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  document_type text not null default 'other',
  original_filename text,
  mime_type text,
  storage_bucket text,
  storage_path text,
  sha256 text,
  extracted_data jsonb not null default '{}'::jsonb,
  extraction_model text,
  created_at timestamptz not null default now(),
  constraint receipt_documents_type_ck check (
    document_type in ('packing_slip', 'coc', 'invoice', 'label', 'other')
  )
);

create index if not exists receipt_documents_receipt_idx on public.receipt_documents (receipt_id);
create index if not exists receipt_documents_client_created_idx on public.receipt_documents (client_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Physical container enhancements
-- ---------------------------------------------------------------------------

alter table public.items
  add column if not exists product_id bigint references public.products(id) on delete restrict,
  add column if not exists receipt_line_id bigint references public.receipt_lines(id) on delete set null,
  add column if not exists source_container_id bigint references public.items(id) on delete set null,
  add column if not exists quality_status text not null default 'released',
  add column if not exists quality_updated_at timestamptz,
  add column if not exists quality_notes text,
  add column if not exists package_type text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.items'::regclass
      and conname = 'items_quality_status_ck'
  ) then
    alter table public.items
      add constraint items_quality_status_ck
      check (quality_status in ('pending_inspection', 'released', 'hold', 'quarantine', 'rejected'));
  end if;
end
$$;

create index if not exists items_product_idx on public.items (product_id);
create index if not exists items_receipt_line_idx on public.items (receipt_line_id);
create index if not exists items_source_container_idx on public.items (source_container_id);
create index if not exists items_quality_client_idx on public.items (client_id, quality_status, archived_at);

-- Build one product-master row per existing client/part number, then attach
-- current containers. Existing active inventory is treated as already released.
insert into public.products (
  client_id,
  part_number,
  name,
  description,
  manufacturer,
  profile_key,
  default_uom,
  attributes
)
select
  ranked.client_id,
  ranked.part_number,
  ranked.name,
  ranked.description,
  ranked.manufacturer,
  ranked.profile_key,
  ranked.uom,
  ranked.product_attributes
from (
  select
    item.client_id,
    trim(item.part_number) as part_number,
    item.name,
    item.description,
    coalesce(item.attributes ->> 'manufacturer', item.attributes ->> 'MFG') as manufacturer,
    coalesce(settings.profile_key, 'general') as profile_key,
    item.uom,
    jsonb_strip_nulls(jsonb_build_object(
      'label_name', coalesce(item.attributes ->> 'label_name', item.attributes ->> 'Label Name'),
      'material_type', coalesce(item.attributes ->> 'material_type', item.attributes ->> 'Type'),
      'color', coalesce(item.attributes ->> 'color', item.attributes ->> 'Color'),
      'additive', coalesce(item.attributes ->> 'additive', item.attributes ->> 'Additive')
    )) as product_attributes,
    row_number() over (
      partition by item.client_id, lower(trim(item.part_number))
      order by item.archived_at nulls first, item.id
    ) as row_rank
  from public.items as item
  left join public.client_inventory_settings as settings
    on settings.client_id = item.client_id
  where item.part_number is not null and length(trim(item.part_number)) > 0
) as ranked
where ranked.row_rank = 1
  and not exists (
    select 1 from public.products as product
    where product.client_id = ranked.client_id
      and lower(trim(product.part_number)) = lower(trim(ranked.part_number))
  );

update public.items as item
set
  product_id = product.id,
  quality_status = coalesce(nullif(item.quality_status, ''), 'released'),
  quality_updated_at = coalesce(item.quality_updated_at, item.updated_at, now())
from public.products as product
where item.product_id is null
  and product.client_id = item.client_id
  and lower(trim(product.part_number)) = lower(trim(item.part_number));

-- ---------------------------------------------------------------------------
-- Receiving / inspection locations
-- ---------------------------------------------------------------------------

with seeds(code, description, barcode, location_type, zone, is_system) as (
  values
    ('RECEIVING-QC', 'Receiving inspection / pending incoming inspection', 'G8L-RECEIVING-QC', 'staging', 'RECEIVING_QC', true),
    ('COMPONENTS-HOLD', 'Internally molded components pending AQL / release', 'G8L-COMPONENTS-HOLD', 'staging', 'COMPONENTS_HOLD', true),
    ('QUARANTINE', 'Quality quarantine area', 'G8L-QUARANTINE', 'staging', 'QUARANTINE', true)
), canonical as (
  select lower(trim(code)) as code_key, min(id) as id
  from public.locations
  group by lower(trim(code))
)
update public.locations as location
set
  description = seeds.description,
  barcode = seeds.barcode,
  location_type = seeds.location_type,
  zone = seeds.zone,
  is_system = seeds.is_system,
  active = true
from seeds
join canonical on canonical.code_key = lower(trim(seeds.code))
where location.id = canonical.id;

with seeds(code, description, barcode, location_type, zone, is_system) as (
  values
    ('RECEIVING-QC', 'Receiving inspection / pending incoming inspection', 'G8L-RECEIVING-QC', 'staging', 'RECEIVING_QC', true),
    ('COMPONENTS-HOLD', 'Internally molded components pending AQL / release', 'G8L-COMPONENTS-HOLD', 'staging', 'COMPONENTS_HOLD', true),
    ('QUARANTINE', 'Quality quarantine area', 'G8L-QUARANTINE', 'staging', 'QUARANTINE', true)
)
insert into public.locations (code, description, barcode, location_type, zone, is_system, active)
select code, description, barcode, location_type, zone, is_system, true
from seeds
where not exists (
  select 1 from public.locations as location
  where lower(trim(location.code)) = lower(trim(seeds.code))
);

-- ---------------------------------------------------------------------------
-- Movement ledger extensions for repack and quality events
-- ---------------------------------------------------------------------------

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conrelid = 'public.inventory_movements'::regclass
      and conname = 'inventory_movements_type_ck'
  ) then
    alter table public.inventory_movements
      drop constraint inventory_movements_type_ck;
  end if;
end
$$;

alter table public.inventory_movements
  add constraint inventory_movements_type_ck
  check (
    movement_type in (
      'opening_balance',
      'import',
      'receipt',
      'transfer',
      'consumption',
      'adjustment',
      'empty',
      'review_resolution',
      'repack_out',
      'repack_in',
      'quality_status_change'
    )
  );

-- ---------------------------------------------------------------------------
-- RLS/service-role access and durable receiving-document bucket
-- ---------------------------------------------------------------------------

alter table public.products enable row level security;
alter table public.product_aliases enable row level security;
alter table public.receipts enable row level security;
alter table public.receipt_lines enable row level security;
alter table public.receipt_documents enable row level security;

revoke all on table public.products from anon, authenticated;
revoke all on table public.product_aliases from anon, authenticated;
revoke all on table public.receipts from anon, authenticated;
revoke all on table public.receipt_lines from anon, authenticated;
revoke all on table public.receipt_documents from anon, authenticated;

grant all privileges on table public.products to service_role;
grant all privileges on table public.product_aliases to service_role;
grant all privileges on table public.receipts to service_role;
grant all privileges on table public.receipt_lines to service_role;
grant all privileges on table public.receipt_documents to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'receiving-documents',
  'receiving-documents',
  false,
  52428800,
  array['application/pdf', 'image/png', 'image/jpeg', 'image/webp']::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

comment on table public.products is
  'Reusable material/part definitions. Physical stock remains represented by items/G8I containers.';
comment on table public.receipts is
  'Receiving transaction header for supplier paperwork and incoming material.';
comment on column public.items.quality_status is
  'Quality disposition separate from physical container status; only released stock is production-available.';
comment on column public.items.source_container_id is
  'Parent physical container when this G8I was created through split/repack.';

commit;
